# Generated by Django 4.2.11 on 2026-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_add_review_comment_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='Ảnh bìa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bài viết Blog',
                'verbose_name_plural': 'Blog Sản Phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
